trigger:
  - main
  - refs/tags/*

variables:
  DotNetVersion: 6.0.100-rc.1.21458.32
  LegacyXamarinAndroidPkg: https://aka.ms/xamarin-android-commercial-d16-10-macos
  LegacyXamarinAndroidVsix: https://aka.ms/xamarin-android-commercial-d16-10-windows
  BUILD_COMMIT: $(Build.SourceVersion)
  BUILD_NUMBER: $(Build.BuildNumber)

resources:
  repositories:
    - repository: internal-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
      ref: refs/heads/main
    - repository: components
      type: github
      name: xamarin/XamarinComponents
      endpoint: xamarin

jobs:
  - template: .ci/build.yml@components
    parameters:
      initSteps:
        - task: UseDotNet@2
          displayName: install .NET $(DotNetVersion)
          inputs:
            version: $(DotNetVersion)
        - pwsh: |
            dotnet workload install android
        - task: JavaToolInstaller@0
          inputs:
            versionSpec: '11'
            jdkArchitectureOption: 'x64'
            jdkSourceOption: 'PreInstalled'
  
      preBuildSteps:
        - pwsh: |
            dotnet tool install --global boots
            boots $(LegacyXamarinAndroidPkg)
          condition: eq(variables['System.JobName'], 'macos')
- ${{ if eq(variables['System.TeamProject'], 'devdiv') }}:
    - template: sign-artifacts/jobs/v2.yml@internal-templates
      parameters:
        dependsOn: [ 'build' ]


