trigger:
  - master
  - refs/tags/*

resources:
  repositories:
    - repository: internal-templates
      type: github
      name: xamarin/yaml-templates
      endpoint: xamarin
    - repository: components
      type: github
      name: xamarin/XamarinComponents
      endpoint: xamarin
      ref: refs/heads/dev/update-tooling

variables:
  BUILD_COMMIT: $(Build.SourceVersion)
  BUILD_NUMBER: $(Build.BuildNumber)

jobs:
  - template: .ci/build.yml@components
    parameters:
      windowsImage: '' # skip building on Windows
  - ${{ if eq(variables['System.TeamProject'], 'devdiv') }}:
    - template: sign-artifacts/jobs/v1.yml@internal-templates
      parameters:
        dependsOn: [ 'build' ]
